require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb",{paths:[process.argv[1]]})',
  __dir__
]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'ALAN_ios' do
  config = use_native_modules!

  # WebRTC needs modular headers so its Swift/Obj-C++ interop works
  pod 'react-native-webrtc',
      :path => '../node_modules/react-native-webrtc',
      :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # For swift-only pods
  # use_frameworks! :linkage => :static
end

post_install do |installer|
  # Run the React Native autolinking pod script:
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )

  # Inject the Swift bridging header so AppDelegate.swift can see
  #    RCTRegisterFrameStreamer(...)
  installer.pods_project.targets.each do |target|
    if target.name == 'ALAN_ios'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] =
          'ALAN_ios/ALAN_ios-Bridging-Header.h'
      end
    end
  end
end
