source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.5'
# platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ALAN_ios' do
  # pod 'react-native-tflite', :path => '../node_modules/react-native-tflite'
  config = use_native_modules!
  
  
  use_react_native!(
    :path => config[:reactNativePath],
    hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|   
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # installer.pods_project.targets.each do |target|
    #   if target.name == 'ALAN_ios'
    #     resources_phase = target.resources_build_phase

    #     file_ref    = installer.pods_project.new_file(File.join(__dir__, 'ALAN_ios', 'MobileNet-v2.tflite'))
    #     file2_ref    = installer.pods_project.new_file(File.join(__dir__, 'ALAN_ios', 'bball.jpg'))

    #     resources_phase.add_file_reference(file_ref)
    #     resources_phase.add_file_reference(file2_ref)
    #   end
    # end
  end
end
