name: Build iOS IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    # 1. Check out the code
    - uses: actions/checkout@v3

    # 2. Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Install NPM dependencies
    - name: Install JS dependencies
      run: npm install
    - name: Export env variables
      run: export USE_FRAMEWORKS=static
      
    # 4. Install CocoaPods in the ios/ directory
    - name: Install CocoaPods
      working-directory: ios
      run: pod install --repo-update

    # 5. Build unsigned .app with signing disabled
    - name: Build unsigned .app
      run: |
        xcodebuild \
          -workspace ios/ALAN_ios.xcworkspace \
          -scheme ALAN_ios \
          -configuration Debug \
          -sdk iphoneos \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          BUILD_DIR=$PWD/build clean build

    # 6. Package the .app into an unsigned IPA
    - name: Package unsigned IPA
      run: |
        BUILD_DIR=build/Debug-iphoneos
        mkdir -p $BUILD_DIR/Payload
        cp -R $BUILD_DIR/ALAN_ios.app $BUILD_DIR/Payload/
        cd $BUILD_DIR
        zip -r ALAN_ios.ipa Payload 
        mv ALAN_ios.ipa $GITHUB_WORKSPACE
        
    # 7. Upload the IPA to download it
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ipa
        path: ALAN_ios.ipa
